sudo: false
dist: trusty

language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

git:
  depth: 1

env:
    global:
        - CC="ccache gcc"
    matrix:
        - PROVIDER=activerecord HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
        - PROVIDER=cake HAS_CACHING_METADATA_SUPPORT=1 HAS_BATCHING_SUPPORT=0
        - PROVIDER=dms HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
        - PROVIDER=doctrine HAS_CACHING_METADATA_SUPPORT=1 HAS_BATCHING_SUPPORT=0
        - PROVIDER=eloquent HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
        - PROVIDER=phalcon HAS_CACHING_METADATA_SUPPORT=1 HAS_BATCHING_SUPPORT=0
        - PROVIDER=propel HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
        - PROVIDER=yii HAS_CACHING_METADATA_SUPPORT=1 HAS_BATCHING_SUPPORT=1
        - PROVIDER=nextrasorm HAS_CACHING_METADATA_SUPPORT=1 HAS_BATCHING_SUPPORT=1

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    exclude:
        - env: PROVIDER=dms HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
          php: 7.2
        - env: PROVIDER=dms HAS_CACHING_METADATA_SUPPORT=0 HAS_BATCHING_SUPPORT=0
          php: nightly

cache:
    # See: https://github.com/travis-ci/travis-ci/issues/8714
    edge: true
    apt: true
    ccache: true
    timeout: 604800
    directories:
        - $HOME/.ccache
        - $HOME/.composer/cache
        - $HOME/pear
        - $HOME/.local/lib

before_install:
    - ulimit -c unlimited -S || true
    - phpenv config-rm xdebug.ini || true
    - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
    - if [[ $PROVIDER == "phalcon" ]]; then bash $TRAVIS_BUILD_DIR/ci/install_phalcon.sh; fi;

install:
    - (cd $TRAVIS_BUILD_DIR/provider/$PROVIDER; composer install --no-dev --no-interaction --prefer-dist --no-suggest --optimize-autoloader)
    - (cd $TRAVIS_BUILD_DIR; composer install --no-dev --no-interaction --prefer-dist --no-suggest --optimize-autoloader)
    - phpenv config-add $TRAVIS_BUILD_DIR/ci/benchmark.ini
    - ls -al `$(phpenv which php-config) --extension-dir`
    - $(phpenv which php) -v
    - $(phpenv which php) -m
    - (cd $(phpenv root); git remote show origin )
    - echo 'SHOW VARIABLES LIKE "%version%"' | mysql -u root

before_script:
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
    - echo 'CREATE DATABASE orm_benchmark CHARSET=utf8 COLLATE=utf8_unicode_ci' | mysql -u root
    - echo "CREATE USER 'enigma'@'%' IDENTIFIED BY 'secret'" | mysql -u root
    - echo "GRANT ALL PRIVILEGES ON orm_benchmark.* TO 'enigma'@'%' WITH GRANT OPTION" | mysql -u root
    - cat schema/orm-benchmark.sql | mysql -u root orm_benchmark

script:
    - cd $TRAVIS_BUILD_DIR
    - php run $PROVIDER read 1
    - php run $PROVIDER read 10
    - php run $PROVIDER create 1
    - php run $PROVIDER create 10
    - if [[ $HAS_CACHING_METADATA_SUPPORT == 1 ]]; then php run $PROVIDER read 1 1; fi;
    - if [[ $HAS_CACHING_METADATA_SUPPORT == 1 ]]; then php run $PROVIDER read 10 1; fi;
    - if [[ $HAS_BATCHING_SUPPORT == 1 ]]; then php run $PROVIDER readBatch 20; fi;
    - if [[ $HAS_BATCHING_SUPPORT == 1 ]]; then php run $PROVIDER readBatch 200; fi;
    - if [[ $HAS_CACHING_METADATA_SUPPORT == 1 && $HAS_BATCHING_SUPPORT == 1 ]]; then php run $PROVIDER readBatch 20 1; fi;
    - if [[ $HAS_CACHING_METADATA_SUPPORT == 1 && $HAS_BATCHING_SUPPORT == 1 ]]; then php run $PROVIDER readBatch 200 1; fi;

notifications:
    # Stop spam me. I already live on Travis CI and GitHub
    email:
        on_success: never
        on_failure: never
